### ISSUE TITLE
TypeError: 'set' object is not a mapping

### ISSUE THREAD

**Issue by PatrikKnizka** [martinbenes1996/slovak-railways#1]
Zdravím, pri kóde ↘️
`import slovakrailways as zsr
print(zsr.track_train("604"))`
to hádže error ↘️
`Traceback (most recent call last):  
  File "d:\python-projects\trains.py", line 9, in <module>  
    print(zsr.track_train("604"))  
  File "D:\Apps\Python\lib\site-packages\slovakrailways\train.py", line 31, in track_train  
    response = common._get_slovakrail(  
  File "D:\Apps\Python\lib\site-packages\slovakrailways\common.py", line 22, in _get_slovakrail  
    headers = {**api_key_hdr, **headers}  
TypeError: 'set' object is not a mapping
`

**Comment by martinbenes1996** [comment]
Díky ;). I'll go for EN comment if it's okay for you.

I am currently redoing the whole package:
* more abstracted interface from the API objects
* caching on client side

I just committed my current version (WIP) in [v2 branch](https://github.com/martinbenes1996/slovakrailways/tree/v2). Feel free to check it out.

Current master will be replaced by the new version. Backwards compatibility will not be sustained. Until then this issue is pending. After releasing, it will be closed.
